name: Build CLIP App

on:
  push:
    tags:
      - "v*" # :: Run when a tag is pushed, like v0.1.0-alpha

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.12.0"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Build and package app
        run: yarn make

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-build
          path: |
            out/make/**/*.exe
            out/make/**/*.msi
            out/make/**/*.dmg
            out/make/**/*.zip
            out/make/**/*.deb
            out/make/**/*.rpm

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *-build/**/*.exe
            *-build/**/*.msi
            *-build/**/*.dmg
            *-build/**/*.zip
            *-build/**/*.deb
            *-build/**/*.rpm
